### ISSUE TITLE
Has a printed circuit board for navigation components.

### ISSUE THREAD

**Issue by tylercondon** [andycondon/rover#6]
- [x] Connections for power
- [x] Connections for Raspberry Pi 2
- [x] Circuit for ATMega 328p
- [x] Circuit for Raspi to ATMega programmer
- [x] Connection for GPS module
- [x] Connections for IR range finders
- [x] Connections for motor control
- [x] Connection for ISP

**Comment by andycondon** [comment]
Done! Actually this was done like a year ago.
